/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function bundless(userOptions?: UserOptions | undefined | null): void
export interface UserOptions {
  /**
   * bundler type
   * @type "esm" | "cjs"
   */
  format?: string | undefined | null
  /**
   * root directory
   * @default process.cwd()
   */
  root?: string | undefined | null
  /**
   * source code directory
   * @default src
   */
  input?: string | undefined | null
  /**
   * output directory
   * @default dist
   */
  output?: string | undefined | null
  /** ignore specific directories & files via ignore syntax */
  ignores?: Array<string> | undefined | null
  /** configure module resolve alias */
  alias?: Record<string, any> | undefined | null
  /** define global constants for source code, like webpack */
  define?: Record<string, any> | undefined | null
}
